package com.example.demo;

import org.jetbrains.annotations.NotNull;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

public class ItemClass {

    /**
     * Immutable projection of a row in the ITEMS table.
     */
    public record Item(int id, String name, String description, double unitPrice, int stock) {
        @Override
        @NotNull
        public String toString() {
            return "Item{" +
                    "id:" + id +
                    ", name:'" + name + '\'' +
                    ", description:'" + description + '\'' +
                    ", unitPrice:" + unitPrice +
                    ", stock:" + stock +
                    '}';
        }
    }

    /**
     * Inserts a new item (ID is auto-generated by the database).
     */
    public static void add(Item i) throws SQLException {
        String sql = "INSERT INTO ITEMS(UnitPrice, Name, Description, Stock) VALUES (?,?,?,?)";
        try (Connection conn = Database.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) { //Tries the connection
            ps.setDouble(1, i.unitPrice());
            ps.setString(2, i.name());
            ps.setString(3, i.description());
            ps.setInt(4, i.stock());
            ps.executeUpdate();
        }
    }

    /**
     * Returns all items ordered by ID.
     */
    public static List<Item> getAll() throws SQLException {
        String sql = "SELECT ID, Name, Description,UnitPrice, Stock FROM ITEMS ORDER BY ID";
        List<Item> list = new ArrayList<>();
        try (Connection conn = Database.getConnection(); PreparedStatement ps = conn.prepareStatement(sql); ResultSet rs = ps.executeQuery()) { //Tries the connection
            while (rs.next()) {
                list.add(new Item(
                        rs.getInt("ID"),
                        rs.getString("Name"),
                        rs.getString("Description"),
                        rs.getDouble("UnitPrice"),
                        rs.getInt("Stock")
                ));
            }
        }
        return list;
    }

    /**
     * Finds an item by ID.
     */
    public static Item getById(int id) throws SQLException {
        String sql = "SELECT ID, Name, Description,UnitPrice, Stock FROM ITEMS WHERE ID = ?";
        try (Connection conn = Database.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) { //Tries the connection
            ps.setInt(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return new Item(
                            rs.getInt("ID"),
                            rs.getString("Name"),
                            rs.getString("Description"),
                            rs.getDouble("UnitPrice"),
                            rs.getInt("Stock")
                    );
                }
            }
        }
        return null;
    }

    /**
     * Updates an existing item (row selected by ID).
     */
    public static void update(Item i) throws SQLException {
        String sql = "UPDATE ITEMS SET Name = ?, Description = ?, UnitPrice = ?, Stock = ? WHERE ID = ?";
        try (Connection conn = Database.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) { //Tries the connection
            ps.setString(1, i.name());
            ps.setString(2, i.description());
            ps.setDouble(3, i.unitPrice());
            ps.setInt(4, i.stock());
            ps.setInt(5, i.id());
            ps.executeUpdate();
        }
    }

    /**
     * Deletes an item by ID.
     */
    public static void delete(int id) throws SQLException {
        String sql = "DELETE FROM ITEMS WHERE ID = ?";
        try (Connection conn = Database.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) { //Tries the connection
            ps.setInt(1, id);
            ps.executeUpdate();
        }
    }
}
