package org.example;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class ItemClass {

    /**
     * Immutable projection of a row in the ITEMS table.
     */
    public record Item(int id, double unitPrice, String name, int stock) {
        @Override
        public String toString() {
            return "Item{" +
                    "id=" + id +
                    ", unitPrice=" + unitPrice +
                    ", name='" + name + '\'' +
                    ", stock=" + stock +
                    '}';
        }
    }

    /**
     * Inserts a new item (ID is auto-generated by the database).
     */
    public static void add(Item i) throws SQLException {
        String sql = "INSERT INTO ITEMS(UnitPrice, Name, Stock) VALUES (?,?,?)";
        try (Connection conn = Database.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) { //Tries the connection
            ps.setDouble(1, i.unitPrice());
            ps.setString(2, i.name());
            ps.setInt(3, i.stock());
            ps.executeUpdate();
        }
    }

    /**
     * Returns all items ordered by ID.
     */
    public static List<Item> getAll() throws SQLException {
        String sql = "SELECT ID, UnitPrice, Name, Stock FROM ITEMS ORDER BY ID";
        List<Item> list = new ArrayList<>();
        try (Connection conn = Database.getConnection(); PreparedStatement ps = conn.prepareStatement(sql); ResultSet rs = ps.executeQuery()) { //Tries the connection
            while (rs.next()) {
                list.add(new Item(
                        rs.getInt("ID"),
                        rs.getDouble("UnitPrice"),
                        rs.getString("Name"),
                        rs.getInt("Stock")
                ));
            }
        }
        return list;
    }

    /**
     * Finds an item by ID.
     */
    public static Item getById(int id) throws SQLException {
        String sql = "SELECT ID, UnitPrice, Name, Stock FROM ITEMS WHERE ID = ?";
        try (Connection conn = Database.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) { //Tries the connection
            ps.setInt(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return new Item(
                            rs.getInt("ID"),
                            rs.getDouble("UnitPrice"),
                            rs.getString("Name"),
                            rs.getInt("Stock")
                    );
                }
            }
        }
        return null;
    }

    /**
     * Updates an existing item (row selected by ID).
     */
    public static void update(Item i) throws SQLException {
        String sql = "UPDATE ITEMS SET UnitPrice = ?, Name = ?, Stock = ? WHERE ID = ?";
        try (Connection conn = Database.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) { //Tries the connection
            ps.setDouble(1, i.unitPrice());
            ps.setString(2, i.name());
            ps.setInt(3, i.stock());
            ps.setInt(4, i.id());
            ps.executeUpdate();
        }
    }

    /**
     * Deletes an item by ID.
     */
    public static void delete(int id) throws SQLException {
        String sql = "DELETE FROM ITEMS WHERE ID = ?";
        try (Connection conn = Database.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) { //Tries the connection
            ps.setInt(1, id);
            ps.executeUpdate();
        }
    }
}
